- hosts: all
  become: yes
  user: "{{ default_user }}"
  tasks:
  - name: 'Update system'
    raw: 'apt-get update'

- hosts: all
  become: yes
  user: "{{ default_user }}"
  roles:
  - { role: initial-setup,	tags: ["initial_setup_role"]}

- hosts: all
  become: yes
  user: "{{ default_user }}"
  roles:
  - { role: create-users,	tags: ["create_users_role"]}

- hosts: all
  user: "{{ k8s_user }}"
  roles:
  - { role: install-k8s,	tags: ["install_k8s_role"]}

- hosts: k8s-master
  user: "{{ k8s_user }}"
  roles:
  - { role: init-cluster,	tags: ["init_cluster_role"]}

- hosts: k8s-workers
  user: "{{ k8s_user }}"
  roles:
  - { role: join-workers,	tags: ["join_workers_role"]}

- hosts: storage-provisioner
  user: "{{ k8s_user }}"
  roles:
  - { role: provisioner,	tags: ["provisioner_role"]}