- name: Ensure group k8s exists
  group:
    name: "{{ k8s_group }}"
    state: present

- name: create the k8s users
  user: 
    name: "{{ k8s_user }}"
    append: yes
    groups: "{{ k8s_group }},sudo"
    state: present 
    createhome: yes 
    shell: /bin/bash

- name: allow k8s users to use sudo without needing a password
  lineinfile:
    dest: /etc/sudoers
    line: "{{ k8s_user }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'

- name: set up authorized keys for k8s users
  authorized_key: 
    user: "{{ k8s_user }}"
    key: "{{ lookup('file', '{{ pub_file }}') }}"
  