- name: Install packages apt
  become: yes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - iputils-arping
    - lvm2
    - net-tools
    - nfs-common
    - python-is-python3
    - wireless-tools