- name: Check if volume is mouted
  shell: mountpoint -q /mnt/storage && echo "mounted" || echo "not mounted"
  register: mount_check
  when:
    uuid_mount is defined

- name: Create mount directory
  become: yes
  file:
    path: /mnt/storage
    owner: nobody
    group: nogroup
    state: directory
    mode: '775'
  when:
    uuid_mount is defined and mount_check.stdout == "not mounted"

- name: Mount volume
  become: yes
  mount:
    path: /mnt/storage
    src: UUID={{ uuid_mount }}
    opts: auto,user,rw
    fstype: ext4
    state: mounted
  when:
    uuid_mount is defined and mount_check.stdout == "not mounted"