- name: Reset Cluster
  become: yes
  command:
    kubeadm reset --force
  register: kubeadmin_init

- name: Initialize Kubernetes master with kubeadm init.
  become: yes
  command:
    kubeadm init
  register: kubeadmin_init

- name: Ensure .kube directory exists.
  file:
    path: ~/.kube
    group: "{{ k8s_group }}"
    state: directory

- name: Copy /etc/kubernetes/admin.conf to ~/.kube/config
  become: yes
  ansible.builtin.copy:
    remote_src: yes
    src:  /etc/kubernetes/admin.conf
    dest: "/home/{{ k8s_user }}/.kube/config"
    owner: "{{ k8s_user }}"
    group: "{{ k8s_group }}"
    mode: '0600'

- name: Configure weavenet networking.
  shell: kubectl apply -f {{ default_kubernetes_cni_weavenet_manifestUrl }}
  register: weavenet_result