- name: Install nerdctl
  become: yes
  shell: |
    wget -qO- https://github.com/containerd/nerdctl/releases/download/v0.22.0/nerdctl-0.22.0-linux-arm64.tar.gz | sudo tar Cxzvvf /usr/local/bin -

- name: enable-linger
  become: yes
  shell: |
    loginctl enable-linger $(whoami)

- name: /etc/subuid and /etc/subgid
  become: yes
  ansible.builtin.script: sub.py
  args:
    executable: python3

- name: delegate.conf
  become: yes
  shell: |
    mkdir -p /etc/systemd/system/user@.service.d
    cat <<EOF | sudo tee /etc/systemd/system/user@.service.d/delegate.conf
    [Service]
    Delegate=cpu cpuset io memory pids
    EOF
    systemctl daemon-reload

- name: Install rootless packages
  become: yes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - slirp4netns
    - uidmap

- name: rootlesskit
  become: yes
  shell: |
    curl -sSL https://github.com/rootless-containers/rootlesskit/releases/download/v1.0.1/rootlesskit-$(uname -m).tar.gz | tar Cxzv /usr/local/bin

- name: containerd rootless
  shell: |
    containerd-rootless-setuptool.sh install